name: ✅Unit Test PR Status Check


defaults:
  run:
    shell: pwsh


on:
  workflow_dispatch:
  pull_request:
    branches:
      - develop
      - preview/v*.*.*-preview.*
      - release/v*.*.*
      - master

jobs:
  unit_test_pr_status_check:
    name: Unit Test PR Status Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    # TODO: Re-enable this one CICD gets the create code coverage feature
    # - name: Run Unit Tests
    #   run: dotnet test "${{ github.workspace }}/Testing/VersionMinerTests/VersionMinerTests.csproj"

    - name: Run Unit Tests
      run: |
        dotnet test "${{ github.workspace }}/Testing/VersionMinerTests/VersionMinerTests.csproj" -c Debug --collect:"XPlat Code Coverage"

  publish-code-coverage:
    runs-on: ubuntu-latest
    name: Publish Code Coverage Results
    steps:
    - uses: actions/checkout@v3

    - name: Execute Unit Tests
      run: dotnet test "${{ github.workspace }}/Testing/VersionMinerTests/VersionMinerTests.csproj" -c Release --collect:"XPlat Code Coverage"

    - uses: codecov/codecov-action@v3
      name: Publish Code Coverage Results
      with:
        token: 6f2006d2-a9c8-4096-ab1b-9ff22873a5a3
        directory: "${{ github.workspace }}/Testing/VersionMinerTests/TestResults/"
        name: "PR Status Check"
        fail_ci_if_error: true
        verbose: true
